devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s"
])

languages([
  'en-US'
#  'de-DE',
#  'it-IT',
#  'es-ES',
#  'fr-FR',
#  'ja-JP',
#  'ko-KR',
#  'pt-PT',
#  'ru-RU',
#  'cmn-Hans',
#  'cmn-Hant'
])

screenshots_path "./screenshots"

clear_previous_screenshots

custom_build_args "GCC_PREPROCESSOR_DEFINITIONS='$(inherited) SNAPSHOT=1'"
